### ISSUE TITLE
Fix asserts involving `ppfAudioData || ppfAudioData[0]`.

### ISSUE THREAD

**Issue by ijc8** [alexanderlerch/2022-MUSI6106#6] opened 2022-02-14 21:49 UTC
As discussed in class (and identified in part by cppcheck), [this assert](https://github.com/alexanderlerch/2022-MUSI6106/blob/07ba5b5c02d291d27e3387ca67253a0296b26fae/src/AudioFileIO/AudioFile.cpp#L129) is a little bit off due to the use of `||`. (The same assert also shows up [here](https://github.com/alexanderlerch/2022-MUSI6106/blob/07ba5b5c02d291d27e3387ca67253a0296b26fae/src/AudioFileIO/AudioFile.cpp#L174), [here](https://github.com/alexanderlerch/2022-MUSI6106/blob/07ba5b5c02d291d27e3387ca67253a0296b26fae/src/AudioFileIO/AudioFile.cpp#L403), and [here](https://github.com/alexanderlerch/2022-MUSI6106/blob/07ba5b5c02d291d27e3387ca67253a0296b26fae/src/AudioFileIO/AudioFile.cpp#L447).)

In particular, if `ppfAudioData` is non-null but `ppfAudioData` _is_ null, the assert will pass, contrary to its intended purpose. (Also, if `ppfAudioData` is null, the program will halt due to dereferencing the null pointer rather than due to the assert failing.)

Replacing `||` with `&&` should fix this. However, as @SileYin suggested, breaking up the assert into two asserts also works and may be more readable.

**Comment by alexanderlerch** [comment] 2022-02-15 22:57
Duplicate of #5

**Comment by alexanderlerch** [comment] 2022-02-15 23:03
closed (see #5)

**Closed by alexanderlerch** 2022-02-15 23:03 UTC
